#!/bin/bash
set -e
. ./activate
echo Running ruff src
ruff check --fix src
echo Running ruff tests
ruff check --fix tests
echo Running black src tests
black src tests
echo Running isort src tests
isort --profile black src tests
echo Running mypy src
mypy src tests
echo Linting complete!
exit 0
